### ISSUE TITLE
j2lint fails with python 3.10

### ISSUE THREAD

**Issue by noredistribution** [aristanetworks/j2lint#23]
```
j2lint templates/eos/
Traceback (most recent call last):
  File "/Users/tamas/.pyenv/versions/3.10.2/bin/j2lint", line 33, in <module>
    sys.exit(load_entry_point('j2lint==0.1', 'console_scripts', 'j2lint')())
  File "/Users/tamas/.pyenv/versions/3.10.2/lib/python3.10/site-packages/j2lint/cli.py", line 150, in run
    collection.extend(RulesCollection.create_from_directory(
  File "/Users/tamas/.pyenv/versions/3.10.2/lib/python3.10/site-packages/j2lint/linter/collection.py", line 86, in create_from_directory
    result.rules = load_plugins(os.path.expanduser(rules_dir))
  File "/Users/tamas/.pyenv/versions/3.10.2/lib/python3.10/site-packages/j2lint/utils.py", line 32, in load_plugins
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/tamas/.pyenv/versions/3.10.2/lib/python3.10/site-packages/j2lint/rules/JinjaTemplateIndentationRule.py", line 7, in <module>
    from j2lint.linter.indenter.node import Node
  File "/Users/tamas/.pyenv/versions/3.10.2/lib/python3.10/site-packages/j2lint/linter/indenter/node.py", line 11, in <module>
    MIDDLE_TAGS = list(flatten([[i[1:-1] for i in JINJA_STATEMENT_TAG_NAMES]]))
  File "/Users/tamas/.pyenv/versions/3.10.2/lib/python3.10/site-packages/j2lint/utils.py", line 106, in flatten
    if (isinstance(el, collections.Iterable) and
AttributeError: module 'collections' has no attribute 'Iterable'
```

**Comment by manuwelakanade** [comment]
This issue is resolved as part of https://github.com/aristanetworks/j2lint/pull/25
